# Generated by Django 5.0.4 on 2024-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('order_status', "Where's my order?"), ('report_issue', 'Report an issue'), ('product_question', 'Product question'), ('order_change', 'Cancel or amend order'), ('other', 'Other')], max_length=200)),
                ('message', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
