# Generated by Django 5.0.4 on 2024-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'In Progress'), ('C', 'Closed')], default='O', max_length=2),
        ),
    ]
